source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'

source/main/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import ProductListView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

]

source/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user: AbstractUser = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    user_info = models.TextField(null=True, blank=True, verbose_name='О себе')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    profile = models.URLField(null=True, blank=True, verbose_name='Профиль ссылка')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = {("can_view_user_list", "Can view the list of users"),}

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

DEFAULT_CATEGORY = 'other'
CATEGORY_CHOICES = (
    (DEFAULT_CATEGORY, 'Разное'),
    ('food', 'Еда'),
    ('tech', 'Бытовая техника'),
    ('tools', 'Инструменты'),
    ('toys', 'Игрушки'),
)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    category = models.CharField(max_length=20, default=DEFAULT_CATEGORY, choices=CATEGORY_CHOICES,
                                verbose_name='Категория')
    picture = models.ImageField(null=True, blank=True, upload_to='pics', verbose_name='Картинка')


    def __str__(self):
        return f'{self.name} - {self.category}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['name']
        permissions = [
            ('can_have_piece_of_pizza', 'Может съесть кусочек пиццы'),
        ]


DEFAULT_RATE = 0
RATE_CHOICES = ((DEFAULT_RATE, 0),
                ("One", 1),
                ("Two", 2),
                ("Three", 3),
                ("Four", 4),
                ("Five", 5)
)


class Review(models.Model):
    product = models.ForeignKey('webapp.Product', related_name='review', on_delete=models.CASCADE, verbose_name='Продукт')
    text = models.TextField(max_length=2000,verbose_name='Текст')
    rate = models.IntegerField(default=DEFAULT_RATE, choices=RATE_CHOICES,verbose_name='Оценка')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1,
                               related_name='reviews', verbose_name='Автор')

    def __str__(self):
        return "{}. {}".format(self.pk, self.text)

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description','category', 'picture']

    def clean(self):
        cleaned_data = super().clean()
        errors = []
        description = cleaned_data.get('description')
        name = cleaned_data.get('name')
        category = cleaned_data.get('category')
        picture = cleaned_data.get('picture')
        if description and name and description == name:
            errors.append(ValidationError("Text  should not duplicate it's name!"))
        if errors:
            raise ValidationError(errors)
        return cleaned_data

source/accounts/views.py
from django.shortcuts import render

# Create your views here.

source/webapp/views.py
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from webapp.forms import ProductForm
from webapp.models import Product


class ProductListView(ListView):
    template_name = 'product/index.html'
    context_object_name = 'products'
    paginate_by = 5

    def get_context_data(self,*, object_list=None, **kwargs):
        return super().get_context_data(object_list=object_list,**kwargs)

    def get_queryset(self):
        data = Product.objects.all()
        return data


class ProductView(DetailView):
    template_name = 'product/product_view.html'
    model = Product
    paginate_reviews_by = 5
    paginate_reviews_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        reviews, page, is_paginated = self.paginate_reviews(self.object)
        context['reviews'] = reviews
        context['page_obj'] = page
        context['is_paginated'] = is_paginated

        return context

    def paginate_reviews(self, product):
        reviews = product.review.all().order_by('-created_at')
        if reviews.count() > 0:
            paginator = Paginator(reviews, self.paginate_reviews_by, orphans=self.paginate_reviews_orphans)
            page_number = self.request.GET.get('page', 1)
            page = paginator.get_page(page_number)
            is_paginated = paginator.num_pages > 1
            return page.object_list, page, is_paginated
        else:
            return reviews, None, False


class ProductCreateView(CreateView):
    template_name = 'product/product_create.html'
    form_class = ProductForm
    model = Product
    permission_required = 'webapp.add_project'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ProductUpdateView(UpdateView):
    template_name = 'product/product_update.html'
    form_class = ProductForm
    model = Product
    permission_required = 'webapp.change_project'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    template_name = 'product/product_delete.html'
    model = Product
    context_object_name = 'project'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_product'

    # def has_permission(self):
    #     return super().has_permission() and self.request.user in self.object.project.user.all()

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
           integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar">
        <ul class="menu">
            <li><a href="{% url 'webapp:index' %}">Home</a></li>
{#        {% if perms.webapp.add_project or request.user in project.user.all%}#}
            <li><a href="{% url 'webapp:product_create' %}">Product Create</a></li>
{#        {% endif %}#}
{#            {% if request.user.is_authenticated %}#}
{#                        <li><a href="{% url 'accounts:detail' request.user.pk %}">Привет, {{ request.user.get_full_name|default:request.user.username }}</a></li>#}
{#                        <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a></li>#}
{#                    {% else %}#}
{#                        <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a></li>#}
{#                        <li class="menu-right"><a href="{% url 'accounts:create' %}?next={{ request.get_full_path }}" class="nav-link">Регистрация</a></li>#}
{#                    {% endif %}#}
{#        {% if perms.webapp.add_project or request.user in project.user.all%}#}
            <li><a href="{% url 'webapp:product_create' %}"></a></li>
{#        {% endif %}#}
{#          {% if perms.accounts.can_view_user_list or request.user in project.user.all%}#}
{#            <li><a href="{% url 'accounts:user_list' %}">User list</a></li>#}
{#        {% endif %}#}
            {% block menu %}{% endblock %}

        {% block menu_links %} {% endblock %}
        </ul>

        {% block search %}
{#            <div class="search-form">#}
{#                <form action="{% url 'index' %}" method="GET">#}
{#                    {{ search_form.search }}#}
{#                    <input type="submit" value="Найти">#}
{#                </form>#}
{#            </div>#}
        {% endblock %}
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
 <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"
            integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
</body>
</html>

source/webapp/templates/partial/form.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}">
        {% csrf_token %}
{% endif %}

        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}

        {% for field in form %}
            {% include 'partial/form_field.html' %}
        {% endfor %}

{% if not fields_only %}
        <br/>
        <input type="submit" value="{{ button_text|default:"Submit" }}"/>
    </form>
{% endif %}

source/webapp/templates/partial/form_field.html
<label for="{{ field.id_for_label }}">{{ field.label }}:</label><br/>
{{ field }}<br/>
{% for error in field.errors %}
    <p class="error">{{ error }}</p>
{% endfor %}
<br/>

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>

source/webapp/templates/product/index.html
{% extends 'base.html' %}

{% block content %}

   <h1>Products</h1>

    {% if is_paginated %}
   {% include 'partial/pagination.html' %}
    {% endif %}
   {% for product in products %}
        <h2><a href="{% url 'webapp:product_view' product.pk %}">{{ product.pk }}.{{ product.name }}</a></h2>
    <p><a href="{% url 'webapp:product_view' product.pk %}">Подробнее</a></p>
   {% endfor %}
      {% if is_paginated %}
   {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/product/product_create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}

{% block content %}
    <h1>Create Product</h1>

    {% include 'partial/form.html' with form_method='post' enctype="multipart/form-data"%}
{% endblock %}

source/webapp/templates/product/product_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:product_view' product.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <h3>Вы уверены, что хотите удалить "{{ product.name }}"?</h3>
    <p>Category {{ product.category }} </p>
       <form action="{% url "webapp:product_delete" product.pk %}" method="post">
        {% csrf_token %}
        <p><input class="btn btn-danger" type="submit" value="Удалить"></p>
        <a href="{% url 'webapp:product_view' product.pk  %}" class="btn btn-primary" role="button" aria-pressed="true">Отмена</a>
    </form>
    <h3>Описание проекта: </h3>
    <p>{{ product.description }}</p>
{% endblock %}

source/webapp/templates/product/product_update.html
{% extends "base.html" %}

{% block title %}Update{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:product_view' product.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <h1>Update Product</h1>

    {% url "webapp:product_update" pk=product.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method='post' button_text='Update' enctype="multipart/form-data/" %}
{% endblock %}

source/webapp/templates/product/product_view.html
{% extends 'base.html' %}
{% block title %}View{% endblock %}
{% block menu %}

{#     <li><a href="{% url 'webapp:task_create' project.pk %}">Create Task</a></li>#}
{% endblock %}
{% block content %}
    <h1>Detailed product page</h1>
    <p><b>Title:</b> {{ product.name}}</p>
     <p><b>Product id:</b> {{ product.pk }}</p>
    <p><b>Description:</b>{{ product.description }}</p>
    <p><b>Product category:</b>{{ product.category }}</p>
    <img class="picture" src="{{ product.picture.url }}" width="250" height="250" alt="picture">


{% comment %}    {% if perms.webapp.change_project and request.user in project.user.all %}{% endcomment %}
    <p><a href="{% url 'webapp:product_update' product.pk %}"  class="btn btn-warning">Update</a></p>
{#    {% endif %}#}
{#    {% if perms.webapp.add_user and request.user in project.user.all %}#}
{#     <p><a href="{% url 'webapp:project_user' project.pk %}"  class="btn btn-warning">Add/Remove User</a></p>#}
{#      {% endif %}#}
{#    {% if perms.webapp.delete_project and request.user in project.user.all%}#}
    <p><a href="{% url 'webapp:product_delete' product.pk %}" class="btn btn-danger">Delete</a></p>
{#    {% endif %}#}
{#        <h3>Tasks</h3>#}
{#        {% if is_paginated %}#}
{#            {% include 'partial/pagination.html' %}#}
{#        {% endif %}#}
{#        {% for task in tasks %}#}
{#            <div class="box">#}
{#                 <h4><a href="{% url 'webapp:task_view' task.pk %}">{{ task.pk }}.{{ task.title }}</a></h4>#}
{#                <div class="pre">{{ task.description }}</div>#}
{#            </div>#}
{#        {% empty %}#}
{#            <p>Нет задач</p>#}
{#        {% endfor %}#}
{#        {% if is_paginated %}#}
{#            {% include 'partial/pagination.html' %}#}
{#        {% endif %}#}

{% endblock %}